# Notes on Chapter 2

Thsi contains information about numpy arrays that I didn't know. 

## Numpy arrays

Let's import numpy and start using it:

In [1]:
import numpy

Unlike lists Numpy arrays are contrained to have all the elements of the same type.  If the types don't match, Numpy will try to upcast. For example, here integers are upcast to floating points.

In [2]:
numpy.array([3.14, 4, 2, 3])

array([ 3.14,  4.  ,  2.  ,  3.  ])

If we want to set the data type to a specific type, we use the `dtype` keyword:

In [3]:
numpy.array([1, 2, 3, 4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

Numpy array can be multidimensional while lists can't. We can generate multi-dimensional arrays also by passing nested list to numpy array. 

In [4]:
numpy.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Subarrays as no copy views

It's important to know that array slices return a "views" of the array rather than copies (this happen in lists). For example:

In [7]:
x2 = numpy.random.randint(10, size=(3, 4))  # Two-dimensional array
print(x2)

[[7 6 6 6]
 [9 4 7 9]
 [0 0 2 4]]


In [8]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[7 6]
 [9 4]]


Now let's see what happen when we modify the subarray:

In [9]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  6]
 [ 9  4]]


In [10]:
print(x2)

[[99  6  6  6]
 [ 9  4  7  9]
 [ 0  0  2  4]]


As you can see the original array has been modified. If we want to avoid this beahaviour, we need to create copies of the array by using the `copy()` method.

In [12]:
#Create a copy
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  6]
 [ 9  4]]


In [13]:
#Modify the copy of the subarray
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  6]
 [ 9  4]]


In [15]:
#We observe no changes in the original one
print(x2)

[[99  6  6  6]
 [ 9  4  7  9]
 [ 0  0  2  4]]
