# Notes on Chapter 2

Thsi contains information about numpy arrays that I didn't know. 

## Numpy arrays

Let's import numpy and start using it:

In [1]:
import numpy

Unlike lists Numpy arrays are contrained to have all the elements of the same type.  If the types don't match, Numpy will try to upcast. For example, here integers are upcast to floating points.

In [2]:
numpy.array([3.14, 4, 2, 3])

array([ 3.14,  4.  ,  2.  ,  3.  ])

If we want to set the data type to a specific type, we use the `dtype` keyword:

In [3]:
numpy.array([1, 2, 3, 4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

Numpy array can be multidimensional while lists can't. We can generate multi-dimensional arrays also by passing nested list to numpy array. 

In [4]:
numpy.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Subarrays as no copy views

It's important to know that array slices return a "views" of the array rather than copies (this happen in lists). For example:

In [5]:
x2 = numpy.random.randint(10, size=(3, 4))  # Two-dimensional array
print(x2)

[[7 5 4 5]
 [0 9 7 0]
 [5 6 4 2]]


In [6]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[7 5]
 [0 9]]


Now let's see what happen when we modify the subarray:

In [7]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 0  9]]


In [8]:
print(x2)

[[99  5  4  5]
 [ 0  9  7  0]
 [ 5  6  4  2]]


As you can see the original array has been modified. If we want to avoid this beahaviour, we need to create copies of the array by using the `copy()` method.

In [9]:
#Create a copy
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 0  9]]


In [10]:
#Modify the copy of the subarray
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 0  9]]


In [11]:
#We observe no changes in the original one
print(x2)

[[99  5  4  5]
 [ 0  9  7  0]
 [ 5  6  4  2]]


## Different ways of reshape arrays

In [12]:
#put numbers from 1-9 in a 3x3 matrix
grid = numpy.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
x = numpy.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [14]:
# row vector via newaxis
x[numpy.newaxis, :]

array([[1, 2, 3]])

In [15]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [16]:
# column vector via newaxis
x[:, numpy.newaxis]

array([[1],
       [2],
       [3]])

## About concatenation of arrays

We will use `numpy.concatenate`, `numpy.vstack`, and `numpy.hstack`. 

In [17]:
x = numpy.array([1, 2, 3])
y = numpy.array([3, 2, 1])

In [18]:
#Concatenate 2 arrays,
#Note: we can concatenate more than 2 at the same time
numpy.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [19]:
#We can also use with 2d arrays
grid = numpy.array([[1, 2, 3],
                 [4, 5, 6]])

numpy.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [20]:
#If we want to concatenate along the sencond axis we do:
numpy.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

If we want to stack array form different dimensions, we can use the stack functions. For example:

In [21]:
x = numpy.array([1, 2, 3])
grid = numpy.array([[9, 8, 7],
                   [6, 5, 4]])

# vertically stack the arrays
numpy.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [22]:
# horizontally stack the arrays
y = numpy.array([[99],
                [99]])
numpy.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])